_format_version: "3.0"
_transform: true

services:
  ######################################
  ### Route Management for Kong
  ######################################
  # Example endpoint: https://api.flowaitecnologia.shop/buffet-lucia
  - name: n8n-instance
    url: https://YOUR-DOMAIN/webhook/n8n-instance
    # Define the routes
    routes:
      # Unique route name
      - name: n8n-instance
        # Remove the "/link" prefix from the URL before forwarding to the backend
        strip_path: true
        # Match all requests starting with "/link/" and also "link/something" due to trailing slash in the URL
        paths:
          - /n8n-instance


########################################################################################
### Users and Access Keys
########################################################################################
consumers:
  - username: YOUR_ADMIN
    keyauth_credentials:
      - key: YOUR_KEY
